### ISSUE TITLE
Add Motion Magic control

### ISSUE THREAD

**Issue by devinvs** [bullbots/InfiniteRechargeJ#18]
Add motion magic control to the drivetrain. This will consist of a couple steps.

1. Create relevant constants in `Constants.java`
2. Configure motion magic constants in `Drivetrain.java`
3. Create a test command that will start motion magic on the drivetrain

**Comment by StephenDay1** [comment]
Didn't I already do this?

**Comment by devinvs** [comment]
Yep.
